/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeAvatar: typeof import('primevue/avatar')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeButtonGroup: typeof import('primevue/buttongroup')['default']
    Primecard: typeof import('primevue/card')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeCarousel: typeof import('primevue/carousel')['default']
    PrimeDivider: typeof import('primevue/divider')['default']
    PrimeDock: typeof import('primevue/dock')['default']
    PrimeDrawer: typeof import('primevue/drawer')['default']
    PrimeForm: typeof import('@primevue/forms/form')['default']
    PrimeImage: typeof import('primevue/image')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMenu: typeof import('primevue/menu')['default']
    PrimeMenubar: typeof import('primevue/menubar')['default']
    PrimeMessage: typeof import('primevue/message')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeSkeleton: typeof import('primevue/skeleton')['default']
    PrimeTab: typeof import('primevue/tab')['default']
    PrimeTabList: typeof import('primevue/tablist')['default']
    PrimeTabs: typeof import('primevue/tabs')['default']
    PrimeToast: typeof import('primevue/toast')['default']
    PrimeToggleSwitch: typeof import('primevue/toggleswitch')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
