/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MyButton: typeof import('primevue/button')['default']
    PrimeAutoComplete: typeof import('primevue/autocomplete')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeDatePicker: typeof import('primevue/datepicker')['default']
    PrimeImage: typeof import('primevue/image')['default']
    PrimeMenu: typeof import('primevue/menu')['default']
    PrimePanel: typeof import('primevue/panel')['default']
    PrimeToggleSwitch: typeof import('primevue/toggleswitch')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
